//! Profile storage, activation, and adopting an existing Ghostty config into a profile.
//!
//! The only file this module ever adds to Ghostty's own config is ONE include
//! line, `config-file = ?ghostty-profiles-active.conf` (the `?` makes a missing
//! file harmless). Everything else lives in the profiles folder.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use crate::confparse;
use crate::paths::Paths;
use crate::presets;
use crate::profile::{ASSET_KEYS, AssetKind, CONF_NAME, Profile, SHADER_KEY, is_appearance_key, is_contained_relative};

pub const INCLUDE_LINE: &str = "config-file = ?ghostty-profiles-active.conf";
/// What the generated config holds while no profile is active.
pub const OFF_CONF: &str = "# Generated by ghostty-profiles: no profile is active, so this file applies nothing.\n";
const MANAGED_COMMENT: &str = "# Managed by ghostty-profiles";
pub const BACKUP_SUFFIX: &str = ".bak-pre-ghostty-profiles";

const LIST_KEYS: [&str; 6] = [
    "font-family",
    "font-family-bold",
    "font-family-italic",
    "font-family-bold-italic",
    "font-feature",
    "custom-shader",
];

fn group(key: &str) -> usize {
    if matches!(key, "background" | "foreground" | "palette" | "theme" | "minimum-contrast" | "bold-color")
        || key.starts_with("cursor-")
        || key.starts_with("selection-")
    {
        0
    } else if key.starts_with("font-") || key.starts_with("adjust-") {
        1
    } else if key.starts_with("background-image") {
        3
    } else if key.starts_with("custom-shader") {
        4
    } else {
        2
    }
}

/// Extra words for the delete confirmation: a bundled preset can be brought back.
pub fn delete_note(name: &str) -> &'static str {
    if presets::profile_names().iter().any(|p| p == name) {
        " (a bundled preset: install-presets brings it back)"
    } else {
        ""
    }
}

pub fn valid_name(name: &str) -> bool {
    let mut chars = name.chars();
    chars.next().is_some_and(|c| c.is_ascii_alphanumeric())
        && chars.all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-'))
        && name.len() <= 64
}

pub(crate) fn atomic_write(path: &Path, text: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let mut tmp = path.as_os_str().to_owned();
    tmp.push(".tmp");
    let tmp = PathBuf::from(tmp);
    fs::write(&tmp, text).with_context(|| format!("writing {}", tmp.display()))?;
    fs::rename(&tmp, path).with_context(|| format!("replacing {}", path.display()))?;
    Ok(())
}

/// Recursive copy that skips symlinks (a shared profile must not be able to pull in other files).
pub(crate) fn copy_dir(src: &Path, dest: &Path) -> Result<()> {
    fs::create_dir_all(dest)?;
    for e in fs::read_dir(src)? {
        let e = e?;
        let ty = e.file_type()?;
        if ty.is_symlink() {
            continue;
        }
        let to = dest.join(e.file_name());
        if ty.is_dir() {
            copy_dir(&e.path(), &to)?;
        } else {
            fs::copy(e.path(), &to)?;
        }
    }
    Ok(())
}

pub struct Store {
    pub paths: Paths,
}

impl Store {
    pub fn new(paths: Paths) -> Self {
        Self { paths }
    }

    pub fn profiles_dir(&self) -> PathBuf {
        self.paths.profiles_dir()
    }

    // ---- profiles -----------------------------------------------------------
    pub fn list_profiles(&self) -> Vec<String> {
        let mut v: Vec<String> = fs::read_dir(self.profiles_dir())
            .map(|rd| {
                rd.flatten()
                    .filter(|e| e.path().join(CONF_NAME).is_file())
                    .map(|e| e.file_name().to_string_lossy().into_owned())
                    .collect()
            })
            .unwrap_or_default();
        v.sort();
        v
    }

    pub fn exists(&self, name: &str) -> bool {
        valid_name(name) && self.profiles_dir().join(name).join(CONF_NAME).is_file()
    }

    pub fn load(&self, name: &str) -> Result<Profile> {
        if !valid_name(name) {
            bail!("invalid profile name '{name}'");
        }
        if !self.exists(name) {
            bail!("no profile named '{name}' (see `ghostty-profiles list`)");
        }
        Profile::load(&self.profiles_dir().join(name))
    }

    pub fn active_name(&self) -> Option<String> {
        let n = fs::read_to_string(self.paths.active_file()).ok()?.trim().to_string();
        (!n.is_empty() && self.exists(&n)).then_some(n)
    }

    /// A new profile; a copy of `from` when given, else empty.
    pub fn new_profile(&self, name: &str, from: Option<&str>) -> Result<Profile> {
        if !valid_name(name) {
            bail!("name must be letters, digits, '.', '_' or '-'");
        }
        if self.exists(name) {
            bail!("profile '{name}' already exists");
        }
        let dest = self.profiles_dir().join(name);
        let mut prof = match from {
            Some(src) => {
                if !self.exists(src) {
                    bail!("no profile named '{src}'");
                }
                copy_dir(&self.profiles_dir().join(src), &dest)?;
                let mut p = Profile::load(&dest)?;
                p.set_description(&format!("copy of {src}"));
                p
            }
            None => {
                let mut p = Profile::new(name, &dest);
                p.set_description("new profile");
                p
            }
        };
        prof.name = name.to_string();
        prof.save()?;
        Ok(prof)
    }

    /// Rename a profile: the whole folder moves, so `images/` and `shaders/` keep their relative paths and
    /// nothing inside needs rewriting. If it is the active profile, the recorded active name and the
    /// generated config (whose asset paths are absolute) are updated, so Ghostty is never left pointing
    /// at a folder that no longer exists. Returns whether the renamed profile is the active one (the
    /// caller should reload Ghostty then).
    pub fn rename(&self, old: &str, new: &str) -> Result<bool> {
        if !self.exists(old) {
            bail!("no profile named '{old}' (see `ghostty-profiles list`)");
        }
        if new.is_empty() {
            bail!("type a name for the profile");
        }
        if !valid_name(new) {
            bail!("name must be letters, digits, '.', '_' or '-' (no spaces or slashes)");
        }
        if new == old {
            bail!("'{old}' already has that name");
        }
        let existing = self.list_profiles();
        if existing.iter().any(|n| n == new) {
            bail!("a profile named '{new}' already exists: pick another name");
        }
        let (from, to) = (self.profiles_dir().join(old), self.profiles_dir().join(new));
        if old.eq_ignore_ascii_case(new) {
            // only the case differs: on a case-insensitive filesystem both names are the same folder,
            // so go through a temporary name
            let mut tmp = from.as_os_str().to_owned();
            tmp.push(".renaming");
            let tmp = PathBuf::from(tmp);
            fs::rename(&from, &tmp)?;
            fs::rename(&tmp, &to)?;
        } else {
            fs::rename(&from, &to)?;
        }
        let was_active = self.active_name().as_deref() == Some(old)
            || fs::read_to_string(self.paths.active_file()).is_ok_and(|n| n.trim() == old);
        if was_active {
            atomic_write(&self.paths.active_file(), new)?;
            self.rerender_active()?;
        }
        Ok(was_active)
    }

    pub fn delete(&self, name: &str) -> Result<()> {
        if !self.exists(name) {
            bail!("no profile named '{name}'");
        }
        if self.active_name().as_deref() == Some(name) {
            bail!("can't delete the active profile; switch to another first");
        }
        fs::remove_dir_all(self.profiles_dir().join(name))?;
        Ok(())
    }

    /// Import a profile folder (e.g. one made by `export`).
    ///
    /// Refuses assets that point outside the folder, and STRIPS every setting that is not an
    /// appearance setting (`command`, `keybind`, `config-file`, ...): a shared profile may change how
    /// Ghostty looks, never what it runs. Returns the name and the keys that were removed.
    pub fn import_profile(&self, src: &Path, name: Option<&str>) -> Result<(String, Vec<String>)> {
        if !src.join(CONF_NAME).is_file() {
            bail!("{} has no {CONF_NAME}", src.display());
        }
        let name = match name {
            Some(n) => n.to_string(),
            None => src.file_name().map(|n| n.to_string_lossy().into_owned()).unwrap_or_default(),
        };
        if !valid_name(&name) {
            bail!("'{name}' is not a valid profile name; pass --name");
        }
        if self.exists(&name) {
            bail!("profile '{name}' already exists");
        }
        let incoming = Profile::load(src)?;
        for l in &incoming.lines {
            if let (Some(k), Some(v)) = (l.key(), l.value())
                && ASSET_KEYS.contains(&k)
                && !is_contained_relative(v)
            {
                bail!("refusing to import: {k} = {v} points outside the profile folder");
            }
        }
        let dest = self.profiles_dir().join(&name);
        copy_dir(src, &dest)?;
        let mut copy = Profile::load(&dest)?;
        let removed = copy.ignored_keys();
        copy.lines.retain(|l| l.is_allowed());
        copy.save()?;
        Ok((name, removed))
    }

    // ---- presets --------------------------------------------------------------
    /// Install the bundled profiles; existing ones are kept unless `force`. Returns the names written.
    pub fn install_presets(&self, force: bool) -> Result<Vec<String>> {
        let mut installed = Vec::new();
        for name in presets::profile_names() {
            let dest = self.profiles_dir().join(&name);
            if dest.exists() {
                if !force {
                    continue;
                }
                fs::remove_dir_all(&dest)?;
            }
            presets::install_profile(&name, &dest)?;
            installed.push(name);
        }
        Ok(installed)
    }

    // ---- activation -------------------------------------------------------------
    /// Clean a profile's shaders folder (see [`Profile::prune`]); the backup goes under `<app dir>/backups/`.
    pub fn prune_profile(
        &self,
        name: &str,
        dry_run: bool,
        drop_orphan_params: bool,
    ) -> Result<crate::profile::PruneReport> {
        let mut prof = self.load(name)?;
        prof.prune(dry_run, &self.paths.app_dir().join("backups"), drop_orphan_params)
    }

    pub fn apply(&self, name: &str) -> Result<PathBuf> {
        self.apply_noted(name).map(|(conf, _)| conf)
    }

    /// Like [`apply`](Self::apply), also returning notes to show the user (for example a shader that no longer exists).
    pub fn apply_noted(&self, name: &str) -> Result<(PathBuf, Vec<String>)> {
        // a profile keeps one shader: tidy it up as it is applied (backed up first, user-written files kept)
        self.prune_profile(name, false, false)?;
        let mut prof = self.load(name)?;
        // a profile pointing at a shader that was removed from the library falls back to none instead of a dead path
        let notes = prof.drop_missing_shaders();
        if !notes.is_empty() {
            prof.save()?;
        }
        prof.render_shaders()?;
        let conf = self.paths.active_conf();
        atomic_write(&conf, &prof.render())?;
        atomic_write(&self.paths.active_file(), name)?;
        self.ensure_linked()?;
        Ok((conf, notes))
    }

    /// Turn the active look off: keep the include line, but make the generated file apply nothing, so
    /// the user's own Ghostty config is all that is in effect. Idempotent, and a no-op (creates
    /// nothing) if no profile was ever applied. True if a profile was active.
    pub fn deactivate(&self) -> Result<bool> {
        let was_active = self.active_name().is_some();
        let conf = self.paths.active_conf();
        if was_active || conf.exists() {
            atomic_write(&conf, OFF_CONF)?;
        }
        match fs::remove_file(self.paths.active_file()) {
            Ok(()) => {}
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => return Err(e.into()),
        }
        Ok(was_active)
    }

    /// Re-render the active profile after an edit. False if nothing is active.
    pub fn rerender_active(&self) -> Result<bool> {
        match self.active_name() {
            Some(n) => {
                let mut prof = self.load(&n)?;
                if !prof.drop_missing_shaders().is_empty() {
                    prof.save()?;
                }
                prof.render_shaders()?;
                atomic_write(&self.paths.active_conf(), &prof.render())?;
                Ok(true)
            }
            None => Ok(false),
        }
    }

    fn main_config(&self) -> PathBuf {
        ["config.ghostty", "config"]
            .iter()
            .map(|n| self.paths.ghostty_dir().join(n))
            .find(|p| p.exists())
            .unwrap_or_else(|| self.paths.ghostty_dir().join("config.ghostty"))
    }

    fn config_files(&self) -> [PathBuf; 2] {
        [self.paths.ghostty_dir().join("config.ghostty"), self.paths.ghostty_dir().join("config")]
    }

    pub fn is_linked(&self) -> bool {
        self.config_files()
            .iter()
            .filter_map(|f| fs::read_to_string(f).ok())
            .any(|t| t.lines().any(|l| l.trim() == INCLUDE_LINE))
    }

    fn backup(&self, path: &Path) -> Result<()> {
        let mut b = path.as_os_str().to_owned();
        b.push(BACKUP_SUFFIX);
        let b = PathBuf::from(b);
        if path.exists() && !b.exists() {
            fs::copy(path, b)?;
        }
        Ok(())
    }

    /// Add the one include line to the main config (idempotent, backed up once). True if it changed.
    pub fn ensure_linked(&self) -> Result<bool> {
        if self.is_linked() {
            return Ok(false);
        }
        let main = self.main_config();
        self.backup(&main)?;
        let mut text = fs::read_to_string(&main).unwrap_or_default();
        if !text.is_empty() && !text.ends_with('\n') {
            text.push('\n');
        }
        text.push_str(&format!("\n{MANAGED_COMMENT}: the active look is loaded from this file.\n{INCLUDE_LINE}\n"));
        atomic_write(&main, &text)?;
        Ok(true)
    }

    /// Remove the include line (and its comment) again. True if anything changed.
    pub fn unlink(&self) -> Result<bool> {
        let mut changed = false;
        for f in self.config_files() {
            let Ok(text) = fs::read_to_string(&f) else { continue };
            let kept: Vec<&str> =
                text.lines().filter(|l| l.trim() != INCLUDE_LINE && !l.starts_with(MANAGED_COMMENT)).collect();
            if kept.len() != text.lines().count() {
                atomic_write(&f, &(kept.join("\n").trim_end().to_string() + "\n"))?;
                changed = true;
            }
        }
        Ok(changed)
    }

    // ---- adopt an existing config as a profile --------------------------------------
    /// Move the appearance keys out of the main Ghostty config files into a new profile.
    ///
    /// Non-appearance settings stay where they are. Referenced shaders and
    /// background images are COPIED into the profile (originals untouched), and
    /// the config files are backed up once. Returns the profile and notes.
    pub fn adopt(&self, name: &str) -> Result<(Profile, Vec<String>)> {
        if !valid_name(name) {
            bail!("invalid profile name '{name}'");
        }
        if self.exists(name) {
            bail!("profile '{name}' already exists");
        }
        let mut notes = Vec::new();
        let mut scalars: Vec<(String, String)> = Vec::new();
        let mut lists: Vec<(String, String)> = Vec::new();
        let mut palette: std::collections::BTreeMap<u8, String> = Default::default();

        let files = [self.paths.ghostty_dir().join("config"), self.paths.ghostty_dir().join("config.ghostty")];
        for f in files.iter().filter(|f| f.is_file()) {
            let lines = confparse::parse(&fs::read_to_string(f)?);
            let (mut kept, mut moved) = (Vec::new(), 0);
            for l in lines {
                match (l.key(), l.value()) {
                    (Some(k), Some(v)) if is_appearance_key(k) => {
                        moved += 1;
                        if k == "palette" {
                            if let Some((i, c)) = v.split_once('=')
                                && let Ok(n) = i.trim().parse::<u8>()
                            {
                                palette.insert(n, c.trim().to_string());
                            }
                        } else if LIST_KEYS.contains(&k) {
                            lists.push((k.to_string(), v.to_string()));
                        } else if let Some(slot) = scalars.iter_mut().find(|(sk, _)| sk == k) {
                            slot.1 = v.to_string();
                        } else {
                            scalars.push((k.to_string(), v.to_string()));
                        }
                    }
                    _ => kept.push(l),
                }
            }
            if moved > 0 {
                self.backup(f)?;
                atomic_write(f, &confparse::dump(&kept))?;
                let fname = f.file_name().unwrap_or_default().to_string_lossy();
                notes.push(format!("moved appearance settings out of {fname} (backup: {fname}{BACKUP_SUFFIX})"));
            }
        }

        let dir = self.profiles_dir().join(name);
        let mut prof = Profile::new(name, &dir);
        prof.set_description("adopted from your Ghostty config");
        let mut entries: Vec<(String, String)> = scalars;
        entries.extend(lists);
        entries.extend(palette.iter().map(|(i, c)| ("palette".to_string(), format!("{i}={c}"))));
        entries.sort_by_key(|(k, _)| group(k));
        for (k, v) in entries {
            prof.lines.push(confparse::entry(&k, &v));
        }
        // make assets self-contained inside the profile
        for i in 0..prof.lines.len() {
            let (Some(k), Some(v)) =
                (prof.lines[i].key().map(str::to_string), prof.lines[i].value().map(str::to_string))
            else {
                continue;
            };
            if !ASSET_KEYS.contains(&k.as_str()) {
                continue;
            }
            let src = prof.resolve_asset(&v);
            if src.is_file() {
                let kind = if k == SHADER_KEY { AssetKind::Shader } else { AssetKind::Image };
                let rel = prof.add_asset(kind, &src, None)?;
                prof.lines[i] = confparse::entry(&k, &rel);
                notes
                    .push(format!("copied {} into the profile", src.file_name().unwrap_or_default().to_string_lossy()));
            } else {
                notes.push(format!("asset not found, left as-is: {v}"));
            }
        }
        prof.save()?;
        Ok((prof, notes))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct Sandbox {
        _td: tempfile::TempDir,
        store: Store,
    }

    fn sandbox() -> Sandbox {
        let td = tempfile::tempdir().unwrap();
        let store = Store::new(Paths::new(td.path().join("config")));
        Sandbox { _td: td, store }
    }

    fn write_ghostty(sb: &Sandbox, file: &str, text: &str) {
        let d = sb.store.paths.ghostty_dir();
        fs::create_dir_all(&d).unwrap();
        fs::write(d.join(file), text).unwrap();
    }

    fn read_ghostty(sb: &Sandbox, file: &str) -> String {
        fs::read_to_string(sb.store.paths.ghostty_dir().join(file)).unwrap()
    }

    #[test]
    fn names_are_validated() {
        for ok in ["shd", "a.b-c_d", "0x"] {
            assert!(valid_name(ok), "{ok}");
        }
        for bad in ["", ".hidden", "-x", "a/b", "a b", "..", &"x".repeat(65)] {
            assert!(!valid_name(bad), "{bad}");
        }
    }

    #[test]
    fn new_copy_delete_and_active_protection() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        let p = s.new_profile("mine", Some("shd")).unwrap();
        assert_eq!(p.description(), "copy of shd");
        assert!(s.exists("mine") && s.list_profiles().contains(&"mine".to_string()));
        assert!(s.new_profile("mine", None).is_err());
        assert!(s.new_profile("../evil", None).is_err());
        s.apply("mine").unwrap();
        assert!(s.delete("mine").is_err(), "the active profile cannot be deleted");
        s.apply("shd").unwrap();
        s.delete("mine").unwrap();
        assert!(!s.exists("mine"));
    }

    #[test]
    fn ensure_linked_is_idempotent_and_backs_up_once() {
        let sb = sandbox();
        let s = &sb.store;
        write_ghostty(&sb, "config", "font-size = 12\n");
        s.install_presets(false).unwrap();
        s.apply("shd").unwrap();
        let after_first = read_ghostty(&sb, "config");
        assert_eq!(after_first.matches(INCLUDE_LINE).count(), 1);
        assert!(after_first.starts_with("font-size = 12\n"));
        assert_eq!(read_ghostty(&sb, "config.bak-pre-ghostty-profiles"), "font-size = 12\n");
        s.apply("shd").unwrap();
        s.apply("calm-dark").unwrap();
        assert_eq!(read_ghostty(&sb, "config"), after_first, "re-applying must not touch the main config again");
        assert!(s.is_linked());
        // unlink removes exactly what we added
        assert!(s.unlink().unwrap());
        assert_eq!(read_ghostty(&sb, "config").trim_end(), "font-size = 12");
        assert!(!s.is_linked());
        assert!(!s.unlink().unwrap());
    }

    #[test]
    fn applying_or_loading_a_missing_profile_fails_and_writes_nothing() {
        let sb = sandbox();
        let s = &sb.store;
        assert!(s.apply("nope").is_err());
        assert!(s.load("nope").is_err());
        assert!(s.apply("../escape").is_err());
        assert!(!s.paths.active_conf().exists(), "no empty active config was written");
        assert!(!s.paths.active_file().exists());
        assert!(!s.paths.ghostty_dir().exists(), "and Ghostty's config dir was not touched");
    }

    #[test]
    fn off_keeps_the_include_applies_nothing_and_is_idempotent() {
        let sb = sandbox();
        let s = &sb.store;
        write_ghostty(&sb, "config", "font-size = 12\nbackground = #111111\n");
        let main_before = read_ghostty(&sb, "config");
        // off with nothing ever applied creates nothing
        assert!(!s.deactivate().unwrap());
        assert!(!s.paths.active_conf().exists() && !s.paths.active_file().exists());

        s.install_presets(false).unwrap();
        s.apply("shd").unwrap();
        let linked = read_ghostty(&sb, "config");
        assert_eq!(s.active_name().as_deref(), Some("shd"));

        for round in 0..3 {
            let was = s.deactivate().unwrap();
            assert_eq!(was, round == 0, "only the first off had something to turn off");
            assert_eq!(s.active_name(), None);
            assert_eq!(fs::read_to_string(s.paths.active_conf()).unwrap(), OFF_CONF);
            assert!(s.is_linked(), "the include stays");
            assert_eq!(read_ghostty(&sb, "config"), linked, "the user's main config is untouched by off");
            assert!(!s.rerender_active().unwrap(), "edits cannot re-activate anything while off");
            assert_eq!(fs::read_to_string(s.paths.active_conf()).unwrap(), OFF_CONF);
        }
        // the user's own settings are all that is left: nothing from the profile is in the generated file
        assert!(!fs::read_to_string(s.paths.active_conf()).unwrap().contains("palette"));
        assert!(linked.starts_with(&main_before));

        // on again, and off again
        s.apply("calm-dark").unwrap();
        assert_eq!(s.active_name().as_deref(), Some("calm-dark"));
        assert!(fs::read_to_string(s.paths.active_conf()).unwrap().contains("background = #1b1e24"));
        assert_eq!(read_ghostty(&sb, "config"), linked, "re-applying adds no second include");
        assert!(s.deactivate().unwrap());
        assert_eq!(fs::read_to_string(s.paths.active_conf()).unwrap(), OFF_CONF);
        // unlink is the stronger step: it removes the include
        assert!(s.unlink().unwrap() && !s.is_linked());
    }

    #[test]
    fn rename_moves_the_whole_folder_and_keeps_images_and_shaders() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        s.new_profile("mine", Some("shd")).unwrap();
        let old = s.profiles_dir().join("mine");
        fs::create_dir_all(old.join("images")).unwrap();
        fs::write(old.join("images/wall.png"), "PIXELS").unwrap();
        let mut p = s.load("mine").unwrap();
        p.set("background-image", "images/wall.png");
        p.save().unwrap();
        s.apply("calm-dark").unwrap();
        let active_before = fs::read_to_string(s.paths.active_conf()).unwrap();

        assert!(!s.rename("mine", "better").unwrap(), "not the active profile");
        let new = s.profiles_dir().join("better");
        assert!(!old.exists() && new.is_dir());
        assert_eq!(fs::read_to_string(new.join("images/wall.png")).unwrap(), "PIXELS");
        assert!(new.join("shaders/xmb-waves.glsl").is_file());
        let conf = fs::read_to_string(new.join(CONF_NAME)).unwrap();
        assert!(
            conf.contains("background-image = images/wall.png")
                && conf.contains("custom-shader = shaders/xmb-waves.glsl"),
            "relative paths untouched: {conf}"
        );
        assert!(s.exists("better") && !s.exists("mine"));
        assert_eq!(s.active_name().as_deref(), Some("calm-dark"));
        assert_eq!(fs::read_to_string(s.paths.active_conf()).unwrap(), active_before, "the live look is untouched");
    }

    #[test]
    fn renaming_the_active_profile_keeps_ghostty_pointing_at_a_real_folder() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        s.apply("shd").unwrap();
        let before = fs::read_to_string(s.paths.active_conf()).unwrap();
        assert!(before.contains(&s.profiles_dir().join("shd/shaders/xmb-waves.glsl").display().to_string()));
        let linked = fs::read_to_string(s.paths.ghostty_dir().join("config.ghostty")).unwrap();

        assert!(s.rename("shd", "ember").unwrap(), "reports that it was active");
        assert_eq!(s.active_name().as_deref(), Some("ember"), "the marker moved with it");
        let after = fs::read_to_string(s.paths.active_conf()).unwrap();
        let shader = s.profiles_dir().join("ember/shaders/xmb-waves.glsl");
        assert!(after.contains(&format!("custom-shader = {}", shader.display())), "{after}");
        assert!(shader.is_file(), "the path Ghostty will read exists");
        assert!(!after.contains(&s.profiles_dir().join("shd").display().to_string()), "no stale path: {after}");
        assert!(after.contains("from profile 'ember'"));
        assert_eq!(
            fs::read_to_string(s.paths.ghostty_dir().join("config.ghostty")).unwrap(),
            linked,
            "the include is untouched"
        );
    }

    #[test]
    fn rename_refuses_bad_names_collisions_and_missing_profiles_and_changes_nothing() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        s.apply("shd").unwrap();
        let (list, active) = (s.list_profiles(), fs::read_to_string(s.paths.active_conf()).unwrap());
        for (old, new, expect) in [
            ("calm-dark", "", "type a name"),
            ("calm-dark", "a/b", "letters, digits"),
            ("calm-dark", "has space", "letters, digits"),
            ("calm-dark", ".hidden", "letters, digits"),
            ("calm-dark", "../escape", "letters, digits"),
            ("calm-dark", "shd", "already exists"),
            ("calm-dark", "calm-dark", "already has that name"),
            ("nope", "x", "no profile named"),
            ("../x", "y", "no profile named"),
        ] {
            let e = s.rename(old, new).unwrap_err().to_string();
            assert!(e.contains(expect), "{old} -> {new:?}: {e}");
        }
        assert_eq!(s.list_profiles(), list, "nothing moved");
        assert_eq!(fs::read_to_string(s.paths.active_conf()).unwrap(), active);
        assert_eq!(s.active_name().as_deref(), Some("shd"));
    }

    #[test]
    fn a_case_only_rename_works_even_on_a_case_insensitive_filesystem() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        s.new_profile("mine", None).unwrap();
        s.rename("mine", "Mine").unwrap();
        assert!(s.list_profiles().contains(&"Mine".to_string()));
        assert!(!s.list_profiles().contains(&"mine".to_string()));
    }

    #[test]
    fn a_renamed_preset_can_be_reinstalled_alongside_it() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        s.rename("calm-dark", "my-calm").unwrap();
        assert_eq!(s.install_presets(false).unwrap(), vec!["calm-dark"], "the original comes back");
        assert!(s.exists("my-calm") && s.exists("calm-dark"));
    }

    // ---- shader parameters ----------------------------------------------------------------

    fn shader_rel(name: &str) -> String {
        format!("shaders/{name}.glsl")
    }

    #[test]
    fn installed_presets_carry_a_parameter_header_with_the_defaults() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        let p = s.load("shd").unwrap();
        let text = fs::read_to_string(p.dir.join("shaders/xmb-waves.glsl")).unwrap();
        assert!(text.contains("const vec3 P_wave_a = vec3(1.000000, 0.419608, 0.101961);"), "the same ember as before");
        assert!(text.contains("const float P_strength = 0.160000;") && text.contains("void mainImage"));
        let st = p.shader_param_state(&shader_rel("xmb-waves")).unwrap();
        assert_eq!(st.schema.params.len(), 5, "opacity first, then the colors and numbers");
        assert_eq!(st.values, vec!["1", "#ff6b1a", "#e31a24", "0.16", "0.35"]);
        // every bundled preset profile's shaders are valid and rendered (no profile references a missing one)
        for n in presets::profile_names() {
            let p = s.load(&n).unwrap();
            for rel in p.shaders() {
                let t = fs::read_to_string(p.resolve_asset(&rel)).unwrap();
                if crate::shaderparams::has_annotations(&t) {
                    assert!(t.contains("P_"), "{n}: {rel} has parameters but no generated header");
                    assert!(p.shader_param_state(&rel).is_some(), "{n}: {rel} annotations do not parse");
                }
            }
        }
    }

    #[test]
    fn setting_a_parameter_writes_the_sidecar_and_regenerates_the_shader_copy() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        let p = s.load("shd").unwrap();
        let rel = shader_rel("xmb-waves");
        p.set_shader_params(&rel, &[("wave_a".into(), "#00ff80".into()), ("strength".into(), "0.3".into())]).unwrap();
        let text = fs::read_to_string(p.dir.join(&rel)).unwrap();
        assert!(
            text.contains("P_wave_a = vec3(0.000000, 1.000000, 0.501961)") && text.contains("P_strength = 0.300000"),
            "{}",
            &text[..300]
        );
        assert_eq!(text.matches("ghostty-profiles parameters").count(), 1, "one header, never stacked");
        let side = fs::read_to_string(p.dir.join("shaders/xmb-waves.params")).unwrap();
        assert!(
            side.contains("wave_a = #00ff80") && side.contains("strength = 0.3") && side.contains("wave_b = #e31a24"),
            "{side}"
        );
        assert_eq!(p.shader_param_state(&rel).unwrap().values[1], "#00ff80");
        // bad values are refused and change nothing
        let before = fs::read_to_string(p.dir.join(&rel)).unwrap();
        for (name, v) in [("wave_a", "zz"), ("strength", "9"), ("strength", "x"), ("nope", "1")] {
            assert!(p.set_shader_params(&rel, &[(name.into(), v.into())]).is_err(), "{name}={v}");
        }
        assert_eq!(fs::read_to_string(p.dir.join(&rel)).unwrap(), before);
        // presets: their values over the defaults; unknown preset refused
        p.apply_shader_preset(&rel, "ocean").unwrap();
        assert_eq!(p.shader_param_state(&rel).unwrap().values, vec!["1", "#2fa8ff", "#4f5bff", "0.18", "0.35"]);
        assert!(p.apply_shader_preset(&rel, "nope").is_err());
        // reset: back to the defaults, sidecar gone
        p.reset_shader_params(&rel).unwrap();
        assert!(!p.dir.join("shaders/xmb-waves.params").exists());
        assert_eq!(p.shader_param_state(&rel).unwrap().values, vec!["1", "#ff6b1a", "#e31a24", "0.16", "0.35"]);
        assert!(fs::read_to_string(p.dir.join(&rel)).unwrap().contains("P_wave_a = vec3(1.000000, 0.419608"));
        // a shader without parameters says so
        assert!(p.set_shader_params("shaders/nothing.glsl", &[("x".into(), "1".into())]).is_err());
    }

    #[test]
    fn apply_regenerates_the_shader_from_the_sidecar_and_the_active_conf_points_at_it() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        s.apply("shd").unwrap();
        let p = s.load("shd").unwrap();
        // someone edits the sidecar by hand (or an import brought it): apply picks it up
        fs::write(p.dir.join("shaders/xmb-waves.params"), "wave_a = #0000ff\nstrength = 0.4\n").unwrap();
        s.apply("shd").unwrap();
        let text = fs::read_to_string(p.dir.join("shaders/xmb-waves.glsl")).unwrap();
        assert!(
            text.contains("P_wave_a = vec3(0.000000, 0.000000, 1.000000)") && text.contains("P_strength = 0.400000")
        );
        assert!(fs::read_to_string(s.paths.active_conf()).unwrap().contains("shaders/xmb-waves.glsl"));
        // rerender_active (after any edit) keeps it in step too
        fs::write(p.dir.join("shaders/xmb-waves.params"), "strength = 0.1\n").unwrap();
        s.rerender_active().unwrap();
        assert!(fs::read_to_string(p.dir.join("shaders/xmb-waves.glsl")).unwrap().contains("P_strength = 0.100000"));
    }

    #[test]
    fn an_untouched_copy_of_an_older_shader_is_upgraded_but_an_edited_one_is_left_alone() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        s.apply("shd").unwrap();
        let p = s.load("shd").unwrap();
        let file = p.dir.join("shaders/xmb-waves.glsl");
        // what version 0.1 installed, byte for byte: no annotations, hard-coded colors
        let old = include_str!("../presets/legacy/xmb-waves-0.1.glsl");
        fs::write(&file, old).unwrap();
        s.apply("shd").unwrap();
        let now = fs::read_to_string(&file).unwrap();
        assert!(now.contains("// @color wave_a") && now.contains("P_wave_a"), "upgraded to the tunable version");
        assert!(p.shader_param_state("shaders/xmb-waves.glsl").is_some());
        // the user's own edit of an old copy is never overwritten
        let edited = format!("{old}\n// my tweak\n");
        fs::write(&file, &edited).unwrap();
        s.apply("shd").unwrap();
        assert_eq!(fs::read_to_string(&file).unwrap(), edited);
        // and an old aurora (the one that washed the top of the window) is upgraded to the background-only one
        s.install_presets(true).unwrap();
        let pa = s.load("aurora-glass").unwrap();
        fs::write(pa.dir.join("shaders/aurora.glsl"), include_str!("../presets/legacy/aurora-0.1.glsl")).unwrap();
        s.apply("aurora-glass").unwrap();
        let up = fs::read_to_string(pa.dir.join("shaders/aurora.glsl")).unwrap();
        assert!(up.contains("bgMask") && up.contains("never blur") || up.contains("can never blur"), "{}", &up[..200]);
    }

    #[test]
    fn a_rendered_copy_from_the_previous_release_is_upgraded_and_a_customised_classic_gradient_keeps_its_look() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        // what a profile installed one release ago holds: the old shader WITH its generated header
        let old = include_str!("../presets/legacy/xmb-waves-0.2.glsl");
        let rendered_old = crate::shaderparams::render(old, &Default::default()).unwrap();
        let file = s.profiles_dir().join("shd/shaders/xmb-waves.glsl");
        fs::write(&file, &rendered_old).unwrap();
        assert!(!rendered_old.contains("P_opacity"));
        s.apply("shd").unwrap();
        let now = fs::read_to_string(&file).unwrap();
        assert!(
            now.contains("P_opacity") && now.contains("gp_textMask"),
            "upgraded to the version with opacity and the text mask"
        );
        assert!(s.load("shd").unwrap().shader_param_state("shaders/xmb-waves.glsl").is_some());

        // xmb-classic: the gradient's two colors changed places to match their labels; a customised pair is carried
        // over swapped so the screen looks the same
        let mut p = s.load("ps3-classic").unwrap();
        let old = include_str!("../presets/legacy/xmb-classic-0.2.glsl");
        let file = p.dir.join("shaders/xmb-classic.glsl");
        fs::write(&file, crate::shaderparams::render(old, &Default::default()).unwrap()).unwrap();
        fs::write(p.dir.join("shaders/xmb-classic.params"), "bg_top = #111111\nbg_bottom = #222222\n").unwrap();
        s.apply("ps3-classic").unwrap();
        p = s.load("ps3-classic").unwrap();
        let st = p.shader_param_state("shaders/xmb-classic.glsl").unwrap();
        let get = |n: &str| st.values[st.schema.params.iter().position(|q| q.name == n).unwrap()].clone();
        assert_eq!((get("bg_top"), get("bg_bottom")), ("#222222".to_string(), "#111111".to_string()));
        // an edited copy of an older shader is never upgraded over the user's work
        let edited = format!(
            "{}\n// mine\n",
            crate::shaderparams::render(include_str!("../presets/legacy/xmb-mono-0.2.glsl"), &Default::default())
                .unwrap()
        );
        let q = s.load("mono-waves").unwrap();
        fs::write(q.dir.join("shaders/xmb-mono.glsl"), &edited).unwrap();
        s.apply("mono-waves").unwrap();
        assert!(fs::read_to_string(q.dir.join("shaders/xmb-mono.glsl")).unwrap().contains("// mine"));
    }

    #[test]
    fn export_and_import_carry_the_values_and_a_hostile_sidecar_still_cannot_inject_code() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        let p = s.load("shd").unwrap();
        p.set_shader_params("shaders/xmb-waves.glsl", &[("wave_a".into(), "#12ab34".into())]).unwrap();
        let dest = sb._td.path().join("shared");
        p.export(&dest, false, false).unwrap();
        assert!(dest.join("shaders/xmb-waves.params").is_file(), "the values travel with the shader");
        assert!(
            fs::read_to_string(dest.join("shaders/xmb-waves.glsl")).unwrap().contains("P_wave_a"),
            "and so does the rendered shader"
        );
        let (name, removed) = s.import_profile(&dest, Some("theirs")).unwrap();
        assert!(removed.is_empty(), "{removed:?}");
        let imported = s.load(&name).unwrap();
        assert_eq!(imported.shader_param_state("shaders/xmb-waves.glsl").unwrap().values[1], "#12ab34");

        // now a hostile one: command lines AND a sidecar full of attempts to smuggle GLSL
        let evil = sb._td.path().join("evil");
        fs::create_dir_all(evil.join("shaders")).unwrap();
        fs::write(
            evil.join("profile.conf"),
            "background = #000000\ncommand = /bin/sh\ncustom-shader = shaders/xmb-waves.glsl\n",
        )
        .unwrap();
        fs::copy(dest.join("shaders/xmb-waves.glsl"), evil.join("shaders/xmb-waves.glsl")).unwrap();
        fs::write(
            evil.join("shaders/xmb-waves.params"),
            "wave_a = #fff); evil_one(); //\nstrength = 0.1; discard;\nextra = float evil_two = 1.0;\nwave_b = #00ff00\n",
        )
        .unwrap();
        let (name, removed) = s.import_profile(&evil, Some("evil")).unwrap();
        assert_eq!(removed, vec!["command"], "the allowlist still applies");
        s.apply(&name).unwrap();
        let text = fs::read_to_string(s.profiles_dir().join("evil/shaders/xmb-waves.glsl")).unwrap();
        for bad in ["evil_one", "evil_two", "discard"] {
            assert!(!text.contains(bad), "{bad} got into the shader");
        }
        assert!(text.contains("P_wave_b = vec3(0.000000, 1.000000, 0.000000)"), "the one valid value was used");
        assert!(
            text.contains("P_wave_a = vec3(1.000000, 0.419608, 0.101961)"),
            "the invalid ones fell back to defaults"
        );
    }

    #[test]
    fn rename_and_copy_keep_the_parameters() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        s.load("shd")
            .unwrap()
            .set_shader_params("shaders/xmb-waves.glsl", &[("wave_b".into(), "#101010".into())])
            .unwrap();
        s.new_profile("copy", Some("shd")).unwrap();
        assert_eq!(s.load("copy").unwrap().shader_param_state("shaders/xmb-waves.glsl").unwrap().values[2], "#101010");
        s.rename("copy", "moved").unwrap();
        assert_eq!(s.load("moved").unwrap().shader_param_state("shaders/xmb-waves.glsl").unwrap().values[2], "#101010");
    }

    #[test]
    fn the_aurora_glass_profile_no_longer_blurs_the_window() {
        let sb = sandbox();
        sb.store.install_presets(false).unwrap();
        let p = sb.store.load("aurora-glass").unwrap();
        assert_eq!(p.get("background-blur"), None, "no blur of whatever is behind the window");
        let shader = fs::read_to_string(p.dir.join("shaders/aurora.glsl")).unwrap();
        let body = crate::shaderparams::strip_header(&shader);
        assert!(
            body.matches("texture(").count() == 1 && !body.contains("texture(iChannel0, uv +"),
            "the shader itself samples only its own pixel (the mask in the generated header does the rest)"
        );
    }

    // ---- one shader per profile, and the tidy-up ----------------------------------------------

    /// A folder like the one a real profile ended up with after browsing every shader: one active shader and
    /// every bundled shader copied in beside it, plus parameter files.
    fn ps3_like(sb: &Sandbox) -> PathBuf {
        let s = &sb.store;
        s.new_profile("ps3", None).unwrap();
        let dir = s.profiles_dir().join("ps3");
        fs::create_dir_all(dir.join("shaders")).unwrap();
        for name in presets::shader_names() {
            fs::write(dir.join("shaders").join(&name), presets::shader_source(&name).unwrap()).unwrap();
        }
        let mut p = s.load("ps3").unwrap();
        p.set("custom-shader", "shaders/xmb-classic.glsl");
        p.set("custom-shader-animation", "true");
        p.save().unwrap();
        p.render_shaders().unwrap(); // the active one has its generated header
        p.set_shader_params("shaders/xmb-classic.glsl", &[("tint".into(), "0.5".into())]).unwrap(); // the operator's change
        fs::write(dir.join("shaders/snow.params"), "opacity = 0.6\nstrength = 0.7\n").unwrap(); // defaults only
        fs::write(dir.join("shaders/fireflies.params"), "strength = 0.2\n").unwrap(); // changed values, shader not in use
        dir
    }

    fn names(dir: &Path) -> Vec<String> {
        let mut v: Vec<String> = fs::read_dir(dir.join("shaders"))
            .unwrap()
            .flatten()
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .collect();
        v.sort();
        v
    }

    #[test]
    fn prune_leaves_a_ps3_like_folder_with_only_the_active_shader_and_what_the_user_changed() {
        let sb = sandbox();
        let s = &sb.store;
        let dir = ps3_like(&sb);
        assert!(names(&dir).len() >= 15, "{:?}", names(&dir));
        // the user edited one bundled shader's copy, and wrote their own
        let edited = format!("{}\n// my tweak\n", presets::shader_source("starfield.glsl").unwrap());
        fs::write(dir.join("shaders/starfield.glsl"), &edited).unwrap();
        fs::write(dir.join("shaders/mine.glsl"), "void mainImage(out vec4 c, in vec2 p) { c = vec4(0.0); }\n").unwrap();
        let before = names(&dir);

        // a dry run lists what would go, and changes nothing (not even a backup)
        let r = s.prune_profile("ps3", true, false).unwrap();
        assert!(r.removed.len() >= 12, "{r:?}");
        assert_eq!(names(&dir), before, "a dry run deletes nothing");
        assert!(!s.paths.app_dir().join("backups").exists(), "and makes no backup");

        // for real: backed up once, then only the right things are left
        let r = s.prune_profile("ps3", false, false).unwrap();
        let after = names(&dir);
        assert_eq!(
            after,
            vec!["mine.glsl", "starfield.glsl", "xmb-classic.glsl", "xmb-classic.params"],
            "the active shader and its changed values, plus what the user wrote or changed: {after:?}"
        );
        assert_eq!(
            fs::read_to_string(dir.join("shaders/starfield.glsl")).unwrap(),
            edited,
            "a user-edited shader survives untouched"
        );
        assert!(
            r.kept_user.contains(&"shaders/mine.glsl".to_string())
                && r.kept_user.contains(&"shaders/starfield.glsl".to_string()),
            "{r:?}"
        );
        assert!(r.kept_params.is_empty(), "{r:?}");
        assert!(
            r.removed.contains(&"shaders/fireflies.params".to_string()),
            "a parameter file whose shader is not in the profile is a leftover and goes (after the backup): {r:?}"
        );
        let backup = r.backup.clone().expect("backed up before the first deletion");
        assert!(backup.starts_with(s.paths.app_dir().join("backups")), "outside the profiles folder: {backup:?}");
        assert!(
            backup.join("shaders/snow.glsl").is_file() && backup.join("profile.conf").is_file(),
            "the backup is the complete original"
        );
        assert!(!s.list_profiles().iter().any(|n| n.contains("bak")), "the backup is not listed as a profile");
        // the active shader still works and still carries the operator's change
        assert!(fs::read_to_string(dir.join("shaders/xmb-classic.glsl")).unwrap().contains("P_tint = 0.500000"));
        assert!(s.load("ps3").unwrap().get("custom-shader-animation").is_some());

        // idempotent: nothing more to do, no second backup
        let again = s.prune_profile("ps3", false, false).unwrap();
        assert!(again.is_empty() && again.backup.is_none(), "{again:?}");
        assert_eq!(names(&dir), after);
        assert!(backup.join("shaders/fireflies.params").is_file(), "the leftover is recoverable from the backup");
    }

    #[test]
    fn prune_never_deletes_a_shader_it_cannot_prove_is_a_bundled_copy() {
        let sb = sandbox();
        let s = &sb.store;
        s.new_profile("p", None).unwrap();
        let dir = s.profiles_dir().join("p");
        fs::create_dir_all(dir.join("shaders")).unwrap();
        fs::write(
            dir.join("shaders/aurora.glsl"),
            "// aurora by someone else\nvoid mainImage(out vec4 c, in vec2 p) {}\n",
        )
        .unwrap();
        fs::write(dir.join("shaders/notes.txt"), "keep me").unwrap();
        fs::write(dir.join("shaders/weird.params"), "opacity = 0.3\n").unwrap();
        fs::create_dir_all(dir.join("shaders/sub")).unwrap();
        fs::write(dir.join("shaders/sub/x.glsl"), "x").unwrap();
        let before = names(&dir);
        let r = s.prune_profile("p", false, false).unwrap();
        assert!(r.removed.is_empty(), "{r:?}");
        assert_eq!(names(&dir), before);
        assert!(
            r.kept_user.contains(&"shaders/aurora.glsl".to_string()),
            "a different file with a bundled name is the user's"
        );
        // an old release's untouched copy is recognised as generated and may go
        fs::write(dir.join("shaders/snow.glsl"), include_str!("../presets/legacy/snow-0.2.glsl")).unwrap();
        let r = s.prune_profile("p", false, false).unwrap();
        assert_eq!(r.removed, vec!["shaders/snow.glsl"]);
    }

    #[test]
    fn a_profile_with_several_shader_lines_keeps_the_first_and_says_which() {
        let sb = sandbox();
        let s = &sb.store;
        s.new_profile("multi", None).unwrap();
        let dir = s.profiles_dir().join("multi");
        fs::create_dir_all(dir.join("shaders")).unwrap();
        for n in ["aurora.glsl", "snow.glsl", "crt-scanlines.glsl"] {
            fs::write(dir.join("shaders").join(n), presets::shader_source(n).unwrap()).unwrap();
        }
        let mut p = s.load("multi").unwrap();
        p.set_all(
            "custom-shader",
            &["shaders/snow.glsl".into(), "shaders/aurora.glsl".into(), "shaders/crt-scanlines.glsl".into()],
        );
        p.save().unwrap();
        let r = s.prune_profile("multi", false, false).unwrap();
        assert_eq!(r.dropped_extra_lines, vec!["shaders/aurora.glsl", "shaders/crt-scanlines.glsl"]);
        let conf = fs::read_to_string(dir.join("profile.conf")).unwrap();
        assert_eq!(conf.matches("custom-shader = ").count(), 1, "{conf}");
        assert!(conf.contains("custom-shader = shaders/snow.glsl"), "the first one stays");
        assert_eq!(names(&dir), vec!["snow.glsl"]);
        assert!(crate::tui::app::prune_message("multi", &r).contains("kept only the first shader"));
    }

    #[test]
    fn apply_tidies_the_profile_and_rendering_is_unchanged_for_the_active_shader() {
        let sb = sandbox();
        let s = &sb.store;
        let dir = ps3_like(&sb);
        s.apply("ps3").unwrap();
        assert!(!names(&dir).contains(&"snow.glsl".to_string()), "{:?}", names(&dir));
        let active = fs::read_to_string(s.paths.active_conf()).unwrap();
        assert!(active.contains("shaders/xmb-classic.glsl"));
        assert!(s.paths.app_dir().join("backups/ps3.bak-pre-prune").is_dir());
    }

    #[test]
    fn use_shader_replaces_and_a_defaults_only_sidecar_is_never_kept() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        let mut p = s.load("shd").unwrap();
        assert_eq!(names(&p.dir), vec!["xmb-waves.glsl"], "an installed preset holds just its shader");
        p.set_shader_params("shaders/xmb-waves.glsl", &[("strength".into(), "0.3".into())]).unwrap();
        assert!(p.dir.join("shaders/xmb-waves.params").is_file());
        // change it back to the default: the sidecar goes
        p.set_shader_params("shaders/xmb-waves.glsl", &[("strength".into(), "0.16".into())]).unwrap();
        assert!(!p.dir.join("shaders/xmb-waves.params").exists());
        // switching shader removes the old rendered copy and its sidecar
        p.set_shader_params("shaders/xmb-waves.glsl", &[("strength".into(), "0.3".into())]).unwrap();
        p.use_shader("snow.glsl").unwrap();
        p.save().unwrap();
        assert_eq!(names(&p.dir), vec!["snow.glsl"], "the old shader and its parameters are gone: {:?}", names(&p.dir));
        assert_eq!(p.shaders(), vec!["shaders/snow.glsl"]);
        // a preset whose values are the defaults leaves no sidecar; another preset does
        p.apply_shader_preset("shaders/snow.glsl", "snowfall").unwrap();
        assert!(!p.dir.join("shaders/snow.params").exists());
        p.apply_shader_preset("shaders/snow.glsl", "blizzard").unwrap();
        assert!(p.dir.join("shaders/snow.params").is_file());
        // none removes everything
        p.clear_shader().unwrap();
        p.save().unwrap();
        assert!(names(&p.dir).is_empty());
        assert!(p.get("custom-shader-animation").is_none() && p.shaders().is_empty());
        // a user's own shader is not removed when another one is selected
        fs::write(p.dir.join("shaders/mine.glsl"), "void mainImage(out vec4 c, in vec2 p) {}\n").unwrap();
        p.use_shader("mine.glsl").unwrap();
        p.use_shader("fireflies.glsl").unwrap();
        assert!(p.dir.join("shaders/mine.glsl").exists(), "something the user wrote is never deleted");
        assert!(p.use_shader("../evil.glsl").is_err() && p.use_shader("nope.glsl").is_err());
    }

    #[test]
    fn export_carries_only_the_active_shader() {
        let sb = sandbox();
        let s = &sb.store;
        let dir = ps3_like(&sb);
        s.apply("ps3").unwrap(); // tidies
        let dest = sb._td.path().join("shared");
        let notes = s.load("ps3").unwrap().export(&dest, false, false).unwrap();
        let mut got: Vec<String> = fs::read_dir(dest.join("shaders"))
            .unwrap()
            .flatten()
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .collect();
        got.sort();
        assert_eq!(got, vec!["xmb-classic.glsl", "xmb-classic.params"], "{got:?} {notes:?}");
        let _ = dir;
    }

    #[test]
    fn the_effects_opacity_is_profile_wide_validated_and_travels_with_the_profile() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        let p = s.load("shd").unwrap();
        assert_eq!(p.effects_opacity(), 1.0);
        p.set_effects_opacity(0.5).unwrap();
        assert_eq!(p.effects_opacity(), 0.5);
        let shader = fs::read_to_string(p.dir.join("shaders/xmb-waves.glsl")).unwrap();
        assert!(shader.contains("P_opacity = 0.500000"), "the shader's own 1.0 times the master 0.5");
        for bad in [-0.1, 1.5, f64::NAN, f64::INFINITY] {
            assert!(p.set_effects_opacity(bad).is_err(), "{bad}");
        }
        assert_eq!(p.effects_opacity(), 0.5);
        // a hand-edited file with nonsense is ignored
        fs::write(p.dir.join("effects.params"), "opacity = 7\n").unwrap();
        assert_eq!(p.effects_opacity(), 1.0);
        fs::write(p.dir.join("effects.params"), "opacity = 0.5\n").unwrap();
        // it travels: export, copy, rename
        let dest = sb._td.path().join("out");
        p.export(&dest, false, false).unwrap();
        assert!(fs::read_to_string(dest.join("effects.params")).unwrap().contains("opacity = 0.5"));
        s.new_profile("c", Some("shd")).unwrap();
        assert_eq!(s.load("c").unwrap().effects_opacity(), 0.5);
        // 1 removes the file again
        p.set_effects_opacity(1.0).unwrap();
        assert!(!p.dir.join("effects.params").exists());
    }

    #[test]
    fn shaders_are_told_the_profiles_background_so_effects_stay_behind_the_text() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        let mut p = s.load("shd").unwrap();
        let c = p.render_context();
        assert_eq!(c.background, (0x2c, 0x2c, 0x2c));
        assert!(!c.background_image);
        let shader = fs::read_to_string(p.dir.join("shaders/xmb-waves.glsl")).unwrap();
        assert!(
            shader.contains("const vec3 P_bg = vec3(0.172549, 0.172549, 0.172549);")
                && shader.contains("P_bg_image = 0.0"),
            "{}",
            &shader[..600]
        );
        // an edit of the background shows up in the header the next time it is rendered
        p.set("background", "#102030");
        p.save().unwrap();
        s.apply("shd").unwrap();
        assert!(
            fs::read_to_string(p.dir.join("shaders/xmb-waves.glsl"))
                .unwrap()
                .contains("P_bg = vec3(0.062745, 0.125490, 0.188235)")
        );
        // a background image switches the shaders to their picture-friendly mask
        p.set("background-image", "images/x.png");
        p.save().unwrap();
        assert!(p.render_context().background_image);
        s.apply("shd").unwrap();
        assert!(fs::read_to_string(p.dir.join("shaders/xmb-waves.glsl")).unwrap().contains("P_bg_image = 1.0"));
        // a theme by name is resolved from the bundled themes; no background at all falls back to Ghostty's default
        let mut q = s.load("calm-dark").unwrap();
        q.remove("background");
        q.set("theme", "Dracula");
        assert_eq!(q.render_context().background, (0x28, 0x2a, 0x36), "Dracula's background");
        q.remove("theme");
        assert_eq!(q.render_context().background, crate::shaderparams::DEFAULT_BACKGROUND);
    }

    #[test]
    fn apply_writes_the_active_conf_with_absolute_assets() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        let conf = s.apply("shd").unwrap();
        let text = fs::read_to_string(conf).unwrap();
        assert!(
            text.contains(&format!(
                "custom-shader = {}",
                s.profiles_dir().join("shd/shaders/xmb-waves.glsl").display()
            ))
        );
        assert_eq!(s.active_name().as_deref(), Some("shd"));
        assert!(s.rerender_active().unwrap());
    }

    #[test]
    fn every_preset_loads_renders_and_has_its_shaders() {
        let sb = sandbox();
        let s = &sb.store;
        let names = presets::profile_names();
        assert!(names.len() >= 4, "{names:?}");
        assert!(names.contains(&"shd".to_string()));
        s.install_presets(false).unwrap();
        for n in &names {
            let p = s.load(n).unwrap();
            assert!(!p.description().is_empty(), "{n} has no description");
            for k in ["background", "foreground"] {
                assert!(p.color(k).is_some(), "{n}: {k}");
            }
            assert_eq!(p.palette().len(), 16, "{n} must set the full 16-color palette");
            let rendered = p.render();
            assert!(rendered.contains("background = "), "{n}");
            for sh in p.shaders() {
                assert!(is_contained_relative(&sh), "{n}: {sh}");
                let f = p.resolve_asset(&sh);
                let src = fs::read_to_string(&f).unwrap_or_else(|_| panic!("{n}: missing {sh}"));
                assert!(src.contains("mainImage"), "{n}: {sh} is not a Ghostty shader");
            }
            assert!(p.image().is_none(), "{n}: presets ship NO background image");
            assert!(!rendered.contains("background-image"), "{n}");
            assert!(!rendered.contains(concat!("/Us", "ers/")), "{n}: a home path leaked into a preset");
        }
        assert!(s.install_presets(false).unwrap().is_empty(), "second install keeps what exists");
        assert_eq!(s.install_presets(true).unwrap().len(), names.len());
    }

    #[test]
    fn shd_matches_the_operators_look_minus_the_image() {
        let sb = sandbox();
        sb.store.install_presets(false).unwrap();
        let p = sb.store.load("shd").unwrap();
        assert_eq!(p.color("background").as_deref(), Some("#2c2c2c"));
        assert_eq!(p.color("foreground").as_deref(), Some("#d8d8d8"));
        assert_eq!(p.color("cursor-color").as_deref(), Some("#ff6a00"));
        assert_eq!(p.get("background-opacity").as_deref(), Some("0.5"));
        assert_eq!(p.get("background-blur").as_deref(), Some("25"));
        assert_eq!(p.shaders(), vec!["shaders/xmb-waves.glsl"]);
        assert_eq!(p.get("custom-shader-animation").as_deref(), Some("true"));
        assert_eq!(p.palette()[&3], "#ff6a00");
    }

    #[test]
    fn adopt_moves_only_appearance_keys_and_backs_up() {
        let sb = sandbox();
        let s = &sb.store;
        let shader = sb._td.path().join("wave.glsl");
        fs::write(&shader, "void mainImage(){}").unwrap();
        write_ghostty(
            &sb,
            "config",
            "foreground = #111111\nkeybind = alt+t=toggle_quick_terminal\nfont-family = Menlo\nfont-family = Symbols\n",
        );
        write_ghostty(
            &sb,
            "config.ghostty",
            &format!(
                "background = #2c2c2c\nforeground = #d8d8d8\nshell-integration = zsh\npalette = 0=#0a0a0a\ncustom-shader = {}\nwindow-padding-x = 8\nkeybind = ctrl+shift+r=reload_config\n",
                shader.display()
            ),
        );
        let (p, notes) = s.adopt("mine").unwrap();
        assert_eq!(p.get("foreground").as_deref(), Some("#d8d8d8"), "config.ghostty wins over config");
        assert_eq!(p.get_all("font-family"), vec!["Menlo", "Symbols"]);
        assert_eq!(p.get("window-padding-x").as_deref(), Some("8"));
        assert_eq!(p.shaders(), vec!["shaders/wave.glsl"]);
        assert!(p.dir.join("shaders/wave.glsl").is_file());
        assert!(shader.is_file(), "the original shader is untouched");
        let main = read_ghostty(&sb, "config");
        assert_eq!(main, "keybind = alt+t=toggle_quick_terminal\n");
        let second = read_ghostty(&sb, "config.ghostty");
        assert_eq!(second, "shell-integration = zsh\nkeybind = ctrl+shift+r=reload_config\n");
        assert!(read_ghostty(&sb, "config.bak-pre-ghostty-profiles").contains("font-family = Menlo"));
        assert!(read_ghostty(&sb, "config.ghostty.bak-pre-ghostty-profiles").contains("background = #2c2c2c"));
        assert!(notes.iter().any(|n| n.contains("backup")));
        assert!(s.adopt("mine").is_err());
        // the profile is complete enough to be applied, and nothing was applied by adopting
        assert_eq!(s.active_name(), None);
    }

    #[test]
    fn import_rejects_profiles_that_point_outside_their_folder() {
        let sb = sandbox();
        let s = &sb.store;
        let bad = sb._td.path().join("bad");
        fs::create_dir_all(&bad).unwrap();
        for evil in
            ["custom-shader = ../../secret.glsl", "background-image = /etc/hosts", "custom-shader = shaders/../../x"]
        {
            fs::write(bad.join(CONF_NAME), format!("{evil}\n")).unwrap();
            assert!(s.import_profile(&bad, None).is_err(), "{evil}");
        }
        fs::write(bad.join(CONF_NAME), "background = #000000\n").unwrap();
        assert_eq!(s.import_profile(&bad, Some("fine")).unwrap().0, "fine");
        assert!(s.import_profile(&bad, Some("fine")).is_err());
    }

    #[test]
    fn import_strips_everything_that_could_run_or_rebind_and_says_so() {
        let sb = sandbox();
        let s = &sb.store;
        let shared = sb._td.path().join("shared");
        fs::create_dir_all(&shared).unwrap();
        fs::write(
            shared.join(CONF_NAME),
            "# description: nice look\nbackground = #101010\ncommand = /bin/sh -c 'open -a Calculator'\ninitial-command = whoami\nkeybind = ctrl+shift+x=text:evil\nconfig-file = /tmp/evil\nfont-size = 13\n",
        )
        .unwrap();
        let (name, removed) = s.import_profile(&shared, Some("theirs")).unwrap();
        assert_eq!(name, "theirs");
        assert_eq!(removed, vec!["command", "config-file", "initial-command", "keybind"]);
        let on_disk = fs::read_to_string(s.profiles_dir().join("theirs").join(CONF_NAME)).unwrap();
        for bad in ["command", "keybind", "config-file", "evil", "Calculator"] {
            assert!(!on_disk.contains(bad), "{bad} survived import:\n{on_disk}");
        }
        assert!(on_disk.contains("background = #101010") && on_disk.contains("font-size = 13"));
        // and applying it writes none of that into the active Ghostty config either
        s.apply("theirs").unwrap();
        let active = fs::read_to_string(s.paths.active_conf()).unwrap();
        for bad in ["command", "keybind", "evil"] {
            assert!(!active.contains(bad), "{bad} reached the active conf:\n{active}");
        }
        // even a hand-edited profile cannot smuggle them past render
        let mut p = s.load("theirs").unwrap();
        p.set("keybind", "ctrl+a=text:evil");
        p.set("command", "evil");
        p.save().unwrap();
        s.apply("theirs").unwrap();
        let active = fs::read_to_string(s.paths.active_conf()).unwrap();
        assert!(!active.contains("keybind") && !active.contains("command"), "{active}");
    }

    #[test]
    fn control_characters_in_values_are_dropped_on_import_and_never_rendered() {
        let sb = sandbox();
        let s = &sb.store;
        let shared = sb._td.path().join("cr");
        fs::create_dir_all(&shared).unwrap();
        // a bare carriage return inside an allowed value, with a smuggled key after it
        fs::write(shared.join(CONF_NAME), "background = #000000\rcommand = evil\nfont-size = 12\n").unwrap();
        let (name, removed) = s.import_profile(&shared, Some("cr")).unwrap();
        assert_eq!(removed, vec!["background"]);
        let on_disk = fs::read_to_string(s.profiles_dir().join(&name).join(CONF_NAME)).unwrap();
        assert!(!on_disk.contains('\r') && !on_disk.contains("command"), "{on_disk:?}");
        assert!(on_disk.contains("font-size = 12"));
        // a hand-placed profile with the same trick is not rendered either
        let dir = s.profiles_dir().join("hand");
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join(CONF_NAME), "foreground = #fff\rcommand = evil\ncursor-color = #123456\n").unwrap();
        s.apply("hand").unwrap();
        let active = fs::read_to_string(s.paths.active_conf()).unwrap();
        assert!(!active.contains('\r') && !active.contains("command") && !active.contains("foreground"), "{active:?}");
        assert!(active.contains("cursor-color = #123456"));
    }

    #[test]
    fn export_then_import_round_trips_a_preset() {
        let sb = sandbox();
        let s = &sb.store;
        s.install_presets(false).unwrap();
        let dest = sb._td.path().join("shd-export");
        s.load("shd").unwrap().export(&dest, false, false).unwrap();
        assert!(!dest.join("images").exists());
        assert_eq!(s.import_profile(&dest, Some("shd2")).unwrap(), ("shd2".to_string(), vec![]));
        assert_eq!(s.load("shd2").unwrap().shaders(), vec!["shaders/xmb-waves.glsl"]);
    }
}

#[cfg(test)]
mod removed_shader_tests {
    use super::*;
    use crate::paths::Paths;

    #[test]
    fn a_profile_pointing_at_a_shader_that_no_longer_exists_applies_with_no_shader_and_a_note() {
        let td = tempfile::tempdir().unwrap();
        let s = Store::new(Paths::new(td.path().join("config")));
        s.install_presets(false).unwrap();
        s.new_profile("old", None).unwrap();
        let dir = s.profiles_dir().join("old");
        // a profile from an earlier release: it names a shader that is neither in its folder nor in the library any more
        let conf = fs::read_to_string(dir.join("profile.conf")).unwrap();
        fs::write(
            dir.join("profile.conf"),
            format!("{conf}\ncustom-shader = shaders/retired-shader.glsl\ncustom-shader-animation = true\n"),
        )
        .unwrap();
        assert!(crate::presets::shader_source("retired-shader.glsl").is_none(), "the shader is gone from the library");
        let (active, notes) = s.apply_noted("old").unwrap();
        assert_eq!(notes.len(), 1, "{notes:?}");
        assert!(notes[0].contains("retired-shader.glsl") && notes[0].contains("no longer available"), "{notes:?}");
        let rendered = fs::read_to_string(active).unwrap();
        assert!(!rendered.contains("ps3-visualizer"), "no dead shader path reaches Ghostty:\n{rendered}");
        assert!(!rendered.contains("custom-shader"), "{rendered}");
        let saved = fs::read_to_string(dir.join("profile.conf")).unwrap();
        assert!(!saved.contains("ps3-visualizer"), "the profile itself is fixed too:\n{saved}");
        // idempotent: nothing more to say next time
        assert!(s.apply_noted("old").unwrap().1.is_empty());
        // a shader file the user still has in the profile folder is theirs and keeps working
        s.new_profile("kept", None).unwrap();
        let kdir = s.profiles_dir().join("kept");
        fs::create_dir_all(kdir.join("shaders")).unwrap();
        fs::write(
            kdir.join("shaders/retired-shader.glsl"),
            "void mainImage(out vec4 c, in vec2 p) { c = vec4(1.0); }\n",
        )
        .unwrap();
        let conf = fs::read_to_string(kdir.join("profile.conf")).unwrap();
        fs::write(kdir.join("profile.conf"), format!("{conf}\ncustom-shader = shaders/retired-shader.glsl\n")).unwrap();
        let (_, notes) = s.apply_noted("kept").unwrap();
        assert!(notes.is_empty(), "{notes:?}");
        assert!(fs::read_to_string(s.paths.active_conf()).unwrap().contains("retired-shader.glsl"));
    }
}
